<B> Unmesh Mulay </B>

PYTHON 5 and Numpy 1

Task 1:
    
1. Write a function to compute 5/0 and use try/except to catch the exceptions.

In [17]:
# Unmesh Mulay 
# Assignment Python 5 & Numpy -1Session
# Task 1 - Program 1 - Date 12th Jan 2019 

def Div(numerator, denometor):
    try:
        return numerator/denometor
    except ZeroDivisionError as e:
        return  "Error - '" + e.args[0] + "'" #"Denometor is zero"

print(Div(5,0))
print("\n\n")


Error - 'division by zero'


Task 1:
    
2.
Implement a Python program to generate all sentences where subject is in ["Americans", "Indians"] 
and verb is in ["Play", "watch"] and the object is in ["Baseball","cricket"].

Hint: Subject,Verb and Object should be declared in the program as shown below.
    
subjects=["Americans ","Indians"]
verbs=["play","watch"]
objects=["Baseball","Cricket"]

Output should come as below:
    
Americans play Baseball.

Americans play Cricket.

Americans watch Baseball.

Americans watch Cricket.

Indians play Baseball.

Indians play Cricket.

Indians watch Baseball.

Indians watch Cricket.

In [1]:
# Unmesh Mulay 
# Assignment Python 5 & Numpy -1Session
# Task 1 - Program 2 - Date 12th Jan 2019 

subjects = ["Americans", "Indians"]
verbs = ["play", "watch"]
objects = ["Baseball", "Cricket"]
print('\n'.join(map(str, list(i + " " + j + " " + k + "." for i in subjects for j in verbs for k in objects)))) 
print("\n\n")

Americans play Baseball.
Americans play Cricket.
Americans watch Baseball.
Americans watch Cricket.
Indians play Baseball.
Indians play Cricket.
Indians watch Baseball.
Indians watch Cricket.





Task 2:
    
1. Write a function so that the columns of the output matrix are powers of the input vector.
The order of the powers is determined by the increasing boolean argument. Specifically, when
increasing is False, the i-th output column is the input vector raised element-wise to the power
of N - i - 1.

HINT: Such a matrix with a geometric progression in each row is named for Alexandre-
Theophile Vandermonde.

In [8]:
# Unmesh Mulay 
# Assignment Python 5 & Numpy 
# Task 2 - Program 1 - Date 13th Jan 2019 

import numpy as np
myArr = np.array([11, 3, 7, 9, 4, 6])

print("Out punt when when increasing boolean argument is True\n")
print(np.vander(myArr, increasing = True))
print("\n\n")
print("Out punt when when increasing boolean argument is False\n")

print(np.vander(myArr, increasing = False))
print("\n\n")

Out punt when when increasing boolean argument is True

[[     1     11    121   1331  14641 161051]
 [     1      3      9     27     81    243]
 [     1      7     49    343   2401  16807]
 [     1      9     81    729   6561  59049]
 [     1      4     16     64    256   1024]
 [     1      6     36    216   1296   7776]]



Out punt when when increasing boolean argument is False

[[161051  14641   1331    121     11      1]
 [   243     81     27      9      3      1]
 [ 16807   2401    343     49      7      1]
 [ 59049   6561    729     81      9      1]
 [  1024    256     64     16      4      1]
 [  7776   1296    216     36      6      1]]



